import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export function generateInvoicePDF(invoice) {
  const doc = new jsPDF();
  const fmt = (n) => `₹${(n || 0).toLocaleString('en-IN')}`;
  
  // Header
  doc.setFillColor(17, 24, 39);
  doc.rect(0, 0, 210, 40, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('INVOICE', 14, 25);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`#${invoice.invoiceNumber}`, 14, 33);
  
  // Status badge
  const statusColors = { PAID: [16, 185, 129], SENT: [59, 130, 246], OVERDUE: [239, 68, 68], DRAFT: [107, 114, 128] };
  const statusColor = statusColors[invoice.status] || [107, 114, 128];
  doc.setFillColor(...statusColor);
  doc.roundedRect(155, 15, 40, 12, 2, 2, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.text(invoice.status || 'DRAFT', 175, 23, { align: 'center' });

  // Reset color
  doc.setTextColor(17, 24, 39);
  
  // Company & Client Info
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Bill To:', 14, 55);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(12);
  doc.text(invoice.clientName || 'Client', 14, 62);
  doc.setFontSize(9);
  doc.setTextColor(107, 114, 128);
  doc.text(invoice.clientEmail || '', 14, 68);
  doc.text(invoice.clientPhone || '', 14, 73);

  // Invoice details (right side)
  doc.setTextColor(17, 24, 39);
  doc.setFontSize(9);
  const rightX = 130;
  doc.setFont('helvetica', 'bold');
  doc.text('Invoice Date:', rightX, 55);
  doc.text('Due Date:', rightX, 62);
  doc.text('Project:', rightX, 69);
  doc.setFont('helvetica', 'normal');
  doc.text(invoice.createdAt ? new Date(invoice.createdAt).toLocaleDateString('en-IN') : new Date().toLocaleDateString('en-IN'), rightX + 35, 55);
  doc.text(invoice.dueDate ? new Date(invoice.dueDate).toLocaleDateString('en-IN') : '—', rightX + 35, 62);
  doc.text(invoice.project?.name || 'General', rightX + 35, 69);

  // Line separator
  doc.setDrawColor(229, 231, 235);
  doc.setLineWidth(0.5);
  doc.line(14, 80, 196, 80);

  // Items table
  const items = invoice.items || [{ description: invoice.description || 'Professional Services', quantity: 1, rate: invoice.totalAmount, amount: invoice.totalAmount }];
  
  autoTable(doc, {
    startY: 85,
    head: [['#', 'Description', 'Qty', 'Rate', 'Amount']],
    body: items.map((item, i) => [
      i + 1,
      item.description || 'Service',
      item.quantity || 1,
      fmt(item.rate || item.amount),
      fmt(item.amount || item.rate)
    ]),
    headStyles: { fillColor: [249, 250, 251], textColor: [55, 65, 81], fontStyle: 'bold', fontSize: 9 },
    bodyStyles: { fontSize: 9, textColor: [17, 24, 39] },
    alternateRowStyles: { fillColor: [249, 250, 251] },
    columnStyles: { 0: { cellWidth: 12 }, 2: { cellWidth: 18, halign: 'center' }, 3: { cellWidth: 30, halign: 'right' }, 4: { cellWidth: 30, halign: 'right' } },
    margin: { left: 14, right: 14 },
    theme: 'plain',
    styles: { cellPadding: 4 }
  });

  const finalY = doc.lastAutoTable.finalY + 10;

  // Totals
  doc.setDrawColor(229, 231, 235);
  doc.line(120, finalY - 5, 196, finalY - 5);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Total Amount:', 120, finalY + 2);
  doc.setFont('helvetica', 'bold');
  doc.text(fmt(invoice.totalAmount), 196, finalY + 2, { align: 'right' });

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(16, 185, 129);
  doc.text('Paid:', 120, finalY + 10);
  doc.text(fmt(invoice.paidAmount), 196, finalY + 10, { align: 'right' });

  doc.setTextColor(239, 68, 68);
  doc.setFont('helvetica', 'bold');
  doc.text('Balance Due:', 120, finalY + 18);
  doc.setFontSize(12);
  doc.text(fmt(invoice.dueAmount), 196, finalY + 18, { align: 'right' });

  // Payment details
  if (invoice.payments && invoice.payments.length > 0) {
    const payY = finalY + 30;
    doc.setTextColor(17, 24, 39);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('Payment History', 14, payY);

    autoTable(doc, {
      startY: payY + 5,
      head: [['Date', 'Amount', 'Method', 'Reference']],
      body: invoice.payments.map(p => [
        new Date(p.paymentDate).toLocaleDateString('en-IN'),
        fmt(p.amount),
        p.method || '—',
        p.transactionId || p.chequeNumber || '—'
      ]),
      headStyles: { fillColor: [236, 253, 245], textColor: [6, 95, 70], fontStyle: 'bold', fontSize: 8 },
      bodyStyles: { fontSize: 8 },
      margin: { left: 14, right: 14 },
      theme: 'plain'
    });
  }

  // Footer
  const pageHeight = doc.internal.pageSize.height;
  doc.setTextColor(156, 163, 175);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by Innonsh Infra', 105, pageHeight - 15, { align: 'center' });
  doc.text(`Generated on ${new Date().toLocaleDateString('en-IN')}`, 105, pageHeight - 10, { align: 'center' });

  // Save
  doc.save(`Invoice_${invoice.invoiceNumber || 'draft'}.pdf`);
}
