import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export function generatePayrollPDF(payrollData, periodLabel = 'Weekly') {
  const doc = new jsPDF();
  const fmt = (n) => `₹${(n || 0).toLocaleString('en-IN')}`;
  
  // Header
  doc.setFillColor(5, 150, 105); // Emerald Green
  doc.rect(0, 0, 210, 40, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('PAYROLL REPORT', 14, 25);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`${periodLabel} Statement - Generated on ${new Date().toLocaleDateString('en-IN')}`, 14, 33);
  
  // Summary Info
  doc.setTextColor(17, 24, 39);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Summary:', 14, 55);
  
  doc.setFont('helvetica', 'normal');
  doc.text(`Total Workers: ${payrollData.totalWorkers || 0}`, 14, 62);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(5, 150, 105);
  doc.text(`Total Payroll: ${fmt(payrollData.totalPayroll)}`, 14, 72);

  // Line separator
  doc.setDrawColor(229, 231, 235);
  doc.setLineWidth(0.5);
  doc.line(14, 80, 196, 80);

  // Workers table
  const rows = (payrollData.breakdown || []).map((item, i) => [
    i + 1,
    `${item.worker?.firstName} ${item.worker?.lastName}`,
    item.worker?.role || 'Worker',
    item.daysWorked || 0,
    fmt(item.worker?.dailyWage),
    fmt(item.totalWage)
  ]);
  
  autoTable(doc, {
    startY: 85,
    head: [['#', 'Worker Name', 'Role', 'Days', 'Rate/Day', 'Net Payable']],
    body: rows,
    headStyles: { fillColor: [249, 250, 251], textColor: [55, 65, 81], fontStyle: 'bold', fontSize: 9 },
    bodyStyles: { fontSize: 9, textColor: [17, 24, 39] },
    alternateRowStyles: { fillColor: [249, 250, 251] },
    columnStyles: { 
        0: { cellWidth: 10 }, 
        3: { halign: 'center' }, 
        4: { halign: 'right' }, 
        5: { halign: 'right', fontStyle: 'bold' } 
    },
    margin: { left: 14, right: 14 },
    theme: 'plain',
    styles: { cellPadding: 4 }
  });

  // Footer
  const pageHeight = doc.internal.pageSize.height;
  doc.setTextColor(156, 163, 175);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by Innonsh Infra - Internal Payroll Statement', 105, pageHeight - 15, { align: 'center' });

  // Save
  doc.save(`Payroll_${periodLabel}_${new Date().toISOString().split('T')[0]}.pdf`);
}
